name: "Export to itch.io"
on: [workflow_dispatch]

env:
  GODOT_EXECUTABLE_URL: https://github.com/godotengine/godot/releases/download/3.5.1-stable/Godot_v3.5.1-stable_linux_headless.64.zip
  GODOT_EXPORT_TEMPLATE_URL: https://github.com/godotengine/godot/releases/download/3.5.1-stable/Godot_v3.5.1-stable_export_templates.tpz

jobs:
  export-html5:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add export presets
        run: |
          printf "${{ secrets.EXPORT_PRESETS }}" > export_presets.cfg
      - name: Web Build
        uses: firebelley/godot-export@v4.2.0
        with:
          godot_executable_download_url: $GODOT_EXECUTABLE_URL
          godot_export_templates_download_url: $GODOT_EXPORT_TEMPLATE_URL
          relative_project_path: ./
          archive_output: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web
      # Upload to itch.io
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: build/web
